version: '3.8'
services:
  mongodb:
    image: mongo:latest
    command: --tlsMode requireTLS --tlsCertificateKeyFile /etc/ssl/mongodb.pem
    volumes:
      - mongodb_data:/data/db
      - /www/server/panel/vhost/cert/test.fzl.my.id:/etc/ssl
    environment:
      - MONGO_INITDB_ROOT_USERNAME="ilyas"
      - MONGO_INITDB_ROOT_PASSWORD="Passmint021"
    ports:
      - 27017:27017
volumes:
  mongodb_data:
