version: '3'
services:
  harvester01:
    privileged: true
    environment:
      - FARMER_HOST=${FARMER_HOST}
    image: harvester:latest
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - /root/ca:/root/ca
      - ./mount/full1.conf:/root/.worker/mount/full1.conf

  harvester02:
    privileged: true
    environment:
      - FARMER_HOST=${FARMER_HOST}
    image: harvester:latest
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - /root/ca:/root/ca
      - ./mount/full2.conf:/root/.worker/mount/full2.conf

  harvester03:
    privileged: true
    environment:
      - FARMER_HOST=${FARMER_HOST}
    image: harvester:latest
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - /root/ca:/root/ca
      - ./mount/full3.conf:/root/.worker/mount/full3.conf
      - ./mount/001.conf:/root/.worker/mount/001.conf
      - ./mount/002.conf:/root/.worker/mount/002.conf
      - ./mount/003.conf:/root/.worker/mount/003.conf
      - ./mount/004.conf:/root/.worker/mount/004.conf
      - ./mount/005.conf:/root/.worker/mount/005.conf
      - ./mount/006.conf:/root/.worker/mount/006.conf
      - ./mount/007.conf:/root/.worker/mount/007.conf
      - ./mount/008.conf:/root/.worker/mount/008.conf

  harvester04:
    privileged: true
    environment:
      - FARMER_HOST=${FARMER_HOST}
    image: harvester:latest
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - /root/ca:/root/ca
      - ./mount/new1.conf:/root/.worker/mount/new1.conf

  harvester05:
    privileged: true
    environment:
      - FARMER_HOST=${FARMER_HOST}
    image: harvester:latest
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - /root/ca:/root/ca
      - ./mount/new2.conf:/root/.worker/mount/new2.conf

  harvester06:
    privileged: true
    environment:
      - FARMER_HOST=${FARMER_HOST}
    image: harvester:latest
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - /root/ca:/root/ca
      - ./mount/new3.conf:/root/.worker/mount/new3.conf
